### ISSUE TITLE
Autodeploy merged/pushed code in to specified branches on server

### ISSUE THREAD

**Issue by Taalaybek** [unilecs/UniLecsBot#13]
Привет
Можно настроить автодеплой кода на сервере при push/merge (хотя это одно и тоже для Github Actions) c помощью Github Actions. Если вам нравится такая идея, я мог бы заняться ею.
Для этого мне понадобится некоторое участие repo owner, в зависимости от типа сервера (Хероку, VPS), настройка ssh ключей и прочего (нужно будет просто в секретные ключи репозитория все записать, данные я не буду видеть, но буду знать что они там)

**Comment by unilecs** [comment]
Добрый день! Да, это классная идея. Напишите мне в телеграме, @albert_davletov

**Comment by unilecs** [comment]
Implemented
