### ISSUE TITLE
Solutions receiving

### ISSUE THREAD

**Issue by LostInKadath** [unilecs/UniLecsBot#8]
А как у нас реализована сейчас фича получения задач от пользователя?

Насколько я понял, идет пересылка ссылки на гист еще одному боту:
```python
    time_at_now = time.strftime("%H:%M:%S %Y.%m.%d", time.localtime())
    form = '''Feedback from {0} - @{1} ({2});\nDate: {3};\nText: {4}'''.format(message.from_user.first_name,
                                                                               message.from_user.username,
                                                                               message.from_user.id,
                                                                               time_at_now,
                                                                               message.text)
    bot.send_message('@unilecs_test', form)
```
А что если нам научить нашего бота заводить репозиторий под каждую задачу и копировать туда решения подписчиков? А потом работать с этим репо - парсить, выуживать решения, отправлять их на тесты... в общем, автоматизировать получение и разбор решений.

У кого какие мысли?

**Comment by LostInKadath** [comment]
Пара наводящих вопросов:
1. Есть ли у гитхаба API? Можно ли научить бота работать с ним? Или придется хранить решения где-то еще?
2. Так как решения принимаются до 10:00 мск, то нельзя просто так взять и при получении ссылки на гист сразу копировать содержимое на репо. Вдруг пользователь захочет что-то добавить. Наверное, надо сделать сбор ссылок до определенного момента, затем по таймеру запретить его и инициировать процесс копирования и разбора решений.

**Comment by Taalaybek** [comment]
можно настроить запуск теста с помощью GitHub Actions, 2000 min в месяц должно хватить проекту
